### Indexing

We already know about indexing of Python sequence types such as lists and tuples.

In [1]:
a = [1, 2, 3, 4]
a[2]

3

We can even index a 2-D list (a list of lists):

In [2]:
m = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

We can pick the second row in `m`:

In [3]:
m[1]

[4, 5, 6]

And from that row we can pick the 3rd element:

In [4]:
m[1][2]

6

Additionally, if the sequence is a mutable sequence, we can replace a value in thge sequence by using an assignment operator:

In [5]:
m[1][2] = 100
m

[[1, 2, 3], [4, 5, 100], [7, 8, 9]]

NumPy arrays work the same way as well.

In [6]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])

In [8]:
a[0]

np.int64(1)

In [9]:
a[1]

np.int64(2)

In [10]:
a[1] = 200

In [11]:
a

array([  1, 200,   3])

And the same thing with a 2-D array:

In [12]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
m[1][1]

np.float64(1.0)

In [14]:
m[1][2] = 100

In [15]:
m

array([[  1.,   0.,   0.],
       [  0.,   1., 100.],
       [  0.,   0.,   1.]])

But NumPy supports a slightly simpler syntax for 2-D (and higher dimension) arrays - instead of using `[i][j]` (and potentially `[i][j][k]` as dimensions/axes get higher), we can just specify both indexes, as a tuple, in the `[]` selector:

In [16]:
m[(1, 2)]

np.float64(100.0)

In [17]:
m[(1, 1)]

np.float64(1.0)

And assignment will work properly as well:

In [18]:
m[(1, 2)] = 300
m

array([[  1.,   0.,   0.],
       [  0.,   1., 300.],
       [  0.,   0.,   1.]])

Now, remember that tuples in Python do not always require to be surrounded by `()` - and so it is in this case, which means we can simply write:

In [19]:
m[1, 2]

np.float64(300.0)

In [20]:
m[1, 2] = 100
m

array([[  1.,   0.,   0.],
       [  0.,   1., 100.],
       [  0.,   0.,   1.]])

One last point to mention is that we have to remember that NumPy arrays have a fixed homogeneous type, so we have to be careful when we replace data to make sure it will fit within the array's data type.

In [21]:
arr = np.array([1, 2, 3, 4], dtype=np.uint8)

This array has a data type of 8-bit unsigned integers - so the range of permissible integers is `[0, 255]`.

And if we try to replace an element with an integer outside of those bounds, we get the usual weirdness with integers wrapping around:

In [22]:
arr[0] = -100
arr

OverflowError: Python integer -100 out of bounds for uint8