### Slicing

Slicing 1 dimensional arrays works the same as slicing Python sequences.

In [1]:
l = [1, 2, 3, 4, 5, 6]

In [2]:
l[0:3]

[1, 2, 3]

In [3]:
l[0::2]

[1, 3, 5]

In [4]:
l[::-1]

[6, 5, 4, 3, 2, 1]

In [5]:
import numpy as np

In [6]:
arr = np.array(l)

In [7]:
arr[0:3]

array([1, 2, 3])

In [8]:
arr[0::2]

array([1, 3, 5])

In [9]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

There is however, one **fundamental** difference between slicing Python sequences and slicing NumPy arrays.

In Python, the slice is totally independent of the original list:

In [10]:
l

[1, 2, 3, 4, 5, 6]

In [11]:
slice_ = l[0:2]
slice_

[1, 2]

In [12]:
slice_[0] = 100
slice_

[100, 2]

In [13]:
l

[1, 2, 3, 4, 5, 6]

As you can see, we modified the slice, but this did not affect the original list.

On the other hand, let's see what happens with NumPy slicing:

In [14]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
slice_ = arr[0:2]
slice_

array([1, 2])

In [16]:
slice_[0] = 100
slice_

array([100,   2])

So the slice was modified, and the original array is...

In [17]:
arr

array([100,   2,   3,   4,   5,   6])

also modified!

The reverse is true too, if we modify the original array:

In [18]:
arr = np.arange(1, 7)
slice_ = arr[3:]
slice_

array([4, 5, 6])

In [19]:
arr[-1] = 60
arr

array([ 1,  2,  3,  4,  5, 60])

In [20]:
slice_

array([ 4,  5, 60])

And as we can see the slice "saw" the change as well.

If we want to "break" this link, we can simply make a copy of the slice:

In [21]:
arr = np.arange(1, 7)
slice_ = arr[3:].copy()
slice_

array([4, 5, 6])

In [22]:
slice_[-1] = 60
slice_

array([ 4,  5, 60])

In [23]:
arr

array([1, 2, 3, 4, 5, 6])

#### 2-D Arrays

Slicing 2-D arrays is a little trickier - the best way to explain it is visually as we saw in the lecture.

But let's try out slicing a few different ways.

Let's start with a square 5 x 5 array of integers from 1 to 25:

In [24]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Let's say we want to select the elements:

```
1 2
6 7
```

This is basically looking at the first two elements of the first two rows of `arr`.

This means we need to slice the first two rows in the first axis (dimension), and the first two elements in the second axis:

In [25]:
arr[0:2, 0:2]

array([[1, 2],
       [6, 7]])

Things can get weirder when we use steps.

For example we want to pick these elements from the array:

```
1  3   5
11 13  15
21 23  25
```

As we can see we are picking every second row (starting at row 0) and every second column (starting at column 0), so we can combine the slices in both axes:

In [26]:
arr[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

We can also combine indexing along one axis with slicing in another.

For example, we can select every second element, starting at the second element, in the third row:

In [27]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr[2, 1::2]

array([12, 14])

And again, keep in mind that the slice is "linked" to the original array:

In [29]:
slice_ = arr[2, 1::2]
slice_

array([12, 14])

In [30]:
slice_[0] = 120
slice_

array([120,  14])

In [31]:
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11, 120,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

A question you're probably asking yourself, is how do I pick a slice of the first, second and fourth rows? You can't use a slice with a step for selecting the rows - a slice cannot slice the rows 0, 1, 2, so what's the solution?

We'll look at that in the next videos on *fancy indexing*.

#### Assigning Values to Slices

We saw earlier that we can replace multiple elements in a Python list by assigning a sequence to a slice:

In [32]:
l = [1, 2, 3, 4, 5, 6]

In [33]:
l[0:3] = [10, 20, 30]
l

[10, 20, 30, 4, 5, 6]

We even saw that we can actually change the number of elements we are replacing - this is possible because Python lists, unlike NumPy arrays, are not of fixed size.

In [34]:
l = [1, 2, 3, 4, 5, 6]
l[0:3] = [10, 20, 30, 40, 50]
l

[10, 20, 30, 40, 50, 4, 5, 6]

We can do something similar with NumPy arrays, but of course we cannot change the size of the original array.

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = np.array([10, 20, 30])
arr

array([10, 20, 30,  4,  5,  6])

We can even use a list instead of an `ndarray`, NumPy will handle that:

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[::2] = [10, 30, 50]
arr

array([10,  2, 30,  4, 50,  6])

But of course we cannot do an assignment that would modify the size of the array:

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = [10, 20, 30, 40]

ValueError: could not broadcast input array from shape (4,) into shape (3,)

We can however, assign a **single** value to a slice - NumPy will just repeat that value as many times as needed to replace every element of the slice with that value.

In [38]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr[::2, ::2]

array([[0, 2],
       [6, 8]])

In [38]:
arr[::2, ::2] = 100
arr

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Anther thing to note is that although an `ndarray` slice is "linked" to the original array, if we replace it with another array, that replaced slice is not linked to that second array.

Let's see an example to illustrate this:

In [39]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20])

In [40]:
arr1[0:2] = arr2
arr1

array([10, 20,  3,  4,  5])

In [41]:
arr2[0] = 100
arr2

array([100,  20])

In [42]:
arr1

array([10, 20,  3,  4,  5])

Of course, this assignment to slices works in higher dimensions too, we just have to make sure we assign an array (or list of lists) that has the same shape as the slice.

In [43]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr[:2, 1:]

array([[1, 2],
       [4, 5]])

In [45]:
arr[:2, 1:] = [[10, 20], [40, 50]]
arr

array([[ 0, 10, 20],
       [ 3, 40, 50],
       [ 6,  7,  8]])

And if we try to assign an array that is not of the same shape, we'll get an exception, even if the total number of elements matches the total number of elements in the slice:

In [46]:
arr[:2, 1:] = [10, 20, 40, 50]

ValueError: could not broadcast input array from shape (4,) into shape (2,2)

Of course, you can always reshape it before doing the assignment:

In [47]:
arr[:2, 1:] = np.array([10, 20, 40, 50]).reshape(2, 2)
arr

array([[ 0, 10, 20],
       [ 3, 40, 50],
       [ 6,  7,  8]])

Lastly, I just want to point out that since NumPy arrays have a fixed homogeneous `dtype`, we have to be careful when we mix types.

For example, suppose we have an array of unsigned 8-bit integers (so range is `[0, 255]`:

In [48]:
arr = np.array([10, 20, 30, 40, 50], dtype=np.uint8)

In [49]:
arr

array([10, 20, 30, 40, 50], dtype=uint8)

In [50]:
arr[0:2] = [-100, 300]
arr

OverflowError: Python integer -100 out of bounds for uint8